### ISSUE TITLE
Disable some functionalities of video/audio controls in course module

### ISSUE THREAD

**Issue by lbkchen** [calblueprint/ros-student#206]
Ideally would look like:
* Can't scrub forwards, but can scrub backwards to already watched content
* No "previous video" or "next video" controls
* No recommended videos shown after video ends
* Audio component has the same features as above

But if scrubbing part is not possible, then alternative would be:
* Disable scrubbing altogether

**Comment by charlesx2013** [comment]
I don't believe scrubbing is possible :(

**Comment by charlesx2013** [comment]
JK, not possible with YT, but possibly vimeo.

**Comment by lbkchen** [comment]
Gonna keep this issue open for video scrubbing

**Comment by lbkchen** [comment]
@charlesx2013 Can you look into disabling keyboard controls for fast-forwarding the video too? kelsey found that you can still use <- and -> keys
